import numpy as np
import cv2
import matplotlib.pyplot as plt
import openslide
import os
from PIL import Image
Image.MAX_IMAGE_PIXELS = 2300000000
level=5

path=r'DProbabilistic Heat Map Generated by Model .npy files'
name="slide name"



image=path+'\\'+name+'.npy'
image = np.load(image)
image = np.transpose(image, [1, 0]) #
# print(image.shape)
print("npy slide_w:", image.shape[0], "npy slide_h:", image.shape[1])
plt.figure(figsize=(image.shape[0] / 100, image.shape[1] / 100), dpi=100)
plt.imshow(image, cmap='jet')
plt.gca().xaxis.set_major_locator(plt.NullLocator())
plt.gca().yaxis.set_major_locator(plt.NullLocator())
plt.subplots_adjust(top=1, bottom=0, right=1, left=0, hspace=0, wspace=0)
plt.margins(0, 0)
# plt.savefig(r"./{}.png".format(name))

plt.show()











